### ISSUE TITLE
Bug in normalizeTrigger

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate-auto-replace#2]
The regexp code doesn't work.

If you want, I can submit a pull request but seems like you could probably fix this quicker if I just let you know.

```js
function normalizeTrigger(trigger) {
  switch (typeOf(trigger)) {
    case 'regexp':
      return (e, data) => !!(e.data && e.data.match(trigger))
    case 'string':
      return (e, data) => data.key ? data.key == trigger : e.data == trigger
  }
}
```

Replace regexp code with:
```js
    case 'regexp':
      return (e, data) => !!(data.key && data.key.match(trigger))
    // may I also suggest adding the following as a nice escape hatch for any unhandled use cases
    case 'function':
      return trigger
```

**Comment by ianstormtaylor** [comment]
Hey @thesunny! When you say doesn't work what do you mean? What's your use case that's failing?

**Comment by ianstormtaylor** [comment]
Just realized that you meant trying to use a RegExp to match a key string, like `/(enter|space)/` but the RegExp is really used for matching characters from `e.data`. I feel like having it be both could be confusing from an API allowance standpoint.

I added the function escape hatch though, so that should solve any use case!
